// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqvibR-KwKa-1GYyNozM4Aveu-1BkOtB8',
    appId: '1:591803136097:web:5b8bfdd0bfc9949c199220',
    messagingSenderId: '591803136097',
    projectId: 'campus-hub-life',
    authDomain: 'campus-hub-life.firebaseapp.com',
    storageBucket: 'campus-hub-life.firebasestorage.app',
    measurementId: 'G-3HCW8DEYYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAj_5OUdqN8PFcBHq4cYml4VG3IxmINns',
    appId: '1:591803136097:android:b3b77290805b7e6d199220',
    messagingSenderId: '591803136097',
    projectId: 'campus-hub-life',
    storageBucket: 'campus-hub-life.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYMb_XBZHTX1GUAAhnOeWMVEuqiU84ZfU',
    appId: '1:591803136097:ios:64de8e50e472ef85199220',
    messagingSenderId: '591803136097',
    projectId: 'campus-hub-life',
    storageBucket: 'campus-hub-life.firebasestorage.app',
    iosBundleId: 'com.example.cs310Project',
  );
}
